version: '3.8'

services:
  app:
    build: .
    container_name: easyaccess_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: easyaccess_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=easyaccess
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
