version: '3.8'

services:
  app:
    build: .
    container_name: easyaccess_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    env_file:
      - .env
    volumes:
      - uploads:${FILES_PATH}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: easyaccess_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:${DB_PATH}

volumes:
  postgres_data:
  uploads:
